### ISSUE TITLE
Slow literal string search case

### ISSUE THREAD

**Issue by bluss** [rust-lang-nursery/regex#103]
Hi, using regex 0.1.41, no features, rustc 1.3.0-nightly (8d432fbf1 2015-07-29)

The following example benchmarks extremely slowly:

haystack: `(0..100_000).map(|_| "a").collect::<String>()`
regex: `(0..30).map(|_| "a").collect::<String>() + "b")`

classic O(n²) string search pathology, except this one is a bit extreme. Benchmark time does not include regex compilation. Byte rate is in haystack searched per second.

```
test bad_naive_long::regex_find                           ... bench:  39,335,695 ns/iter (+/- 3,039,414) = 2 MB/s
```

**Comment by bluss** [comment]
libstd str::find benchmark for the same example is `299,126 ns/iter (+/- 4,469) = 334 MB/s`

**Comment by bluss** [comment]
Source for the benchmark is [this repo](https://github.com/bluss/scratchspace/tree/857f8449038c433a6f25f781ca7e57ac8c486ba3), my string search junkyard.

**Comment by BurntSushi** [comment]
Without looking too closely, my guess is that only the first 15 characters in the regex are extracted as a literal prefix (it's capped so that the Aho-Corasick automaton doesn't use a ridiculous amount of memory). Since that isn't the whole regex, it has to jump into the regex machinery.

I'm probably being overeager with `memchr`, so it's probably running `memchr` for each character in the haystack, diving into the regex machinery to check for a match, failing, and starting again.

I think the prefix extraction needs to be smarter (or check for simple cases like "the regex is just one literal").

**Comment by bluss** [comment]
True. BMH on the whole literal would reject this extremely quickly, it's in fact a best case for BMH

**Comment by BurntSushi** [comment]
I added benchmarks that demonstrates the bad behavior. `long_needle1` and `long_needle2`.

**Comment by bluss** [comment]
I think this one is fixed.

The various substring search cases from twoway show that regex is of course fast almost all the way across the board:

https://travis-ci.org/bluss/scratchspace/jobs/171761917

There's few cases where regex does a worse than `str::find`'s substring search, but for example:

```
test aaab_in_aab::find                      ... bench:     731,806 ns/iter (+/- 3,853) = 409 MB/s
test aaab_in_aab::regex_find                ... bench:   1,183,472 ns/iter (+/- 5,727) = 253 MB/s
```

The input is:

- haystack: "aab".repeat(100_000)
- pattern: "aaab".repeat(100)

**Comment by BurntSushi** [comment]
From looking at those benchmarks, it's clear there's more work to be done. At the moment, we sell out on some cases (which have a high concentration in your benchmark) to get better use out of `memchr` in more common cases. Specifically by calling `memchr` on the rarest byte in a string, where "rarest" is determined based on a pre-computed frequency table.

It looks like we're at least out of the woods on pathologically slow behavior though, so I'll close this. Thanks for the heads up!
