### ISSUE TITLE
Stars of alts of capturing groups not capturing all matches

### ISSUE THREAD

**Issue by flaviusb** [rust-lang-nursery/regex#139]
This may be a bug in my understanding of the Rust regex api, rather than in the api itself.

The bug seems to be that if I have a starred non capturing group, which contains an alt of capturing groups, I only ever get at most one result for each capturing group, plus a zeroth result for the entire match, where I should get a match for every non-overlapping capture, plus a zeroth result for the entire match.

So, if I have

```Rust
fn check2(data: &str) {
  let matcher = Regex::new("\\A(?:(a)|(b))*").unwrap();
  println!("A regex with groups:");
  for caps in matcher.captures_iter(data) {
    println!("A group containing:  ");
    for cap in caps.iter() {
      println!("{:?}", cap);
    }
  }
}
```
Which I run like so:
```Rust
  check2("a");
  check2("aaaaa");
  check2("b");
  check2("bbbbbb");
  check2("ab");
  check2("ba");
  check2("aba");
  check2("bab");
```

I get this as output:

```
A regex with groups:
A group containing:  
Some("a")
Some("a")
None
A regex with groups:
A group containing:  
Some("aaaaa")
Some("a")
None
A regex with groups:
A group containing:  
Some("b")
None
Some("b")
A regex with groups:
A group containing:  
Some("bbbbbb")
None
Some("b")
A regex with groups:
A group containing:  
Some("ab")
Some("a")
Some("b")
A regex with groups:
A group containing:  
Some("ba")
Some("a")
Some("b")
A regex with groups:
A group containing:  
Some("aba")
Some("a")
Some("b")
A regex with groups:
A group containing:  
Some("bab")
Some("a")
Some("b")
```

That is, I get the whole match, plus two submatches, but not the rest of the submatches, and the submatches are not in the order they appear in the input - that is, if an a and a b are matched, instead of getting two results, with:

```
A group containing:
None
Some("b")
A group containing:
Some("a")
None
```

I get one result, like so:

```
A regex with groups:
A group containing:  
Some("ba")
Some("a")
Some("b")
```

Versions:
rustc 1.4.0
cargo 0.6.0 (e1ed995 2015-10-22)
regex-syntax v0.2.2
libc v0.2.2
memchr v0.1.7
aho-corasick v0.4.0
regex v0.1.43

**Comment by BurntSushi** [comment]
As far as I can see, this is working as intended. (I also just checked your examples in a Python interpreter, and the behavior is identical.) Let me try to explain.

First and foremost, your `captures_iter` should definitely only be returning one result given all of your inputs. In particular, your anchoring your regex to the beginning of the string, so as soon as the first match occurs, all subsequent matches will fail because they won't be at the beginning of the string. *Additionally*, `*` is greedy, so if your regex is `(a|b)*` and your input is some combination of `a`s and `b`s exclusively, then `(a|b)*` is going to match the entire input in the first go, which will produce exactly one input.

Secondly, the submatches are determined by whatever was last matched. This is *really* hard to see given your regex/inputs. Instead, I propose that you change your regex to `^(?:([a-m])|([n-z]))*`. If you match that against `xyz`, you'll get one match. The `0` capture will be `xyz`, the `1` capture will be `None` and the `2` capture will be `z`. Using the same regex, try the input `xaybz`. The `0` capture will be `xaybz`, but the `1` capture will be `b` and the `2` capture will be `z`.

Thirdly, when you call `caps.iter()`, it iterates over captures in the order in which they were *defined*. Since your `(a)` capture was defined before your `(b)` capture, iterating over the captures in a match will always produce the `(a)` capture first, even if a `b` occurred before the first `a` in the input.

**Comment by flaviusb** [comment]
Thanks for the fast, thorough response.

I think where I went wrong was the assumtion that a capturing group that appears inside a star with an alt can match multiple times with only one application of the regex, because of the alt, where the matched groups are only generated by multiple matches of the full regex - so, I though you would end up with a sliding window like thing with the star, but actually you end up with just whatever was last matched.
