### ISSUE TITLE
Add `Regex::captures_match`

### ISSUE THREAD

**Issue by dhardy** [rust-lang-nursery/regex#150]
This would be the *captures* version of *is_match*, as opposed to *find*.

I.e.

    /// Similar to `captures()` but only matches the entire string. If the pattern does
    /// not match the entire string, `None` is returned; otherwise this returns the
    /// capture groups corresponding to the match in text.
    /// Capture group 0 always corresponds to the entire match.
    /// 
    /// You should only use captures if you need access to submatches. Otherwise,
    /// `is_match` is faster for testing whether the string matches.
    fn capturesmatch<'t>(&self, text: &'t str) -> Option<Captures<'t>>

**Comment by dhardy** [comment]
Note: some regex engines support `^` and `$` to match the beginning of the string and the end of the string respectively. This didn't work when I tried it with `captures` but that might just be a bug?

**Comment by BurntSushi** [comment]
***All*** matching methods in this crate rewrite regexes from `re` to `.*?re.*?`. I did it that way to avoid combinatoric explosion of methods, and it also keeps the matching semantics within the regex itself. You never have to wonder, "should I use re.search or re.match?" From the docs:

> All searching is done with an implicit `.*?` at the beginning and end of an expression. To force an expression to match the whole string (or a prefix or a suffix), you must use an anchor like `^` or `$` (or `\A` and `\z`).

So with that said, your proposal here isn't quite accurate, since `capturesmatch` would not match the behavior of `is_match`.

**Comment by BurntSushi** [comment]
> Note: some regex engines support ^ and $ to match the beginning of the string and the end of the string respectively. This didn't work when I tried it with captures but that might just be a bug?

@dhardy I missed this on my first read through at work. Could you show an example of something that didn't work like you expected?

**Comment by dhardy** [comment]
Okay, I take that back. It seems to work.
