### ISSUE TITLE
find_iter positions are erronously confusing

### ISSUE THREAD

**Issue by Fiedzia** [rust-lang-nursery/regex#159]
I'm trying to implement some text processing where I'm removing things matching regexp, unless they are in places marked as protected (so keep protected words untouched). It annoys me to no end, as well as generates huge amount of bugs,
that find_iter returns byte positions instead of char positions.
This forces me to maintain my own byte-to-char offset mappings, and its not exactly pleasant experience. Can find_iter_chars be added to the api? (I suppose its to late to change find_iter, though I think byte offsets have no place in text processing anymore).

**Comment by BurntSushi** [comment]
@Fiedzia Thanks for reaching out to us!

So, I'm having a difficult time understanding exactly what is causing you pain. Slicing strings in Rust by bytes should be very easy! Could you perhaps show us some code that you find particularly annoying? We might be able to help you make it better. :-)

Note that all of the string matching functions in `std` also return byte offsets!

> Can find_iter_chars be added to the api?

Unfortunately not. While the underlying engines are guaranteed to return correct byte offsets into UTF-8 encoded strings, they do not necessarily always operate on sequences of Unicode scalar values. For example, one particular optimization involves a call to `memchr`, which is blissfully ignorant of UTF-8, but also *really* fast. The only way for `regex` to implement `find_iter_chars` would be to limit itself to processing one Unicode scalar value at a time and never using fast routines like `memchr`, or to use `memchr` and keep a byte -> codepoint offset map internally. Neither of these are acceptable solutions in my view.

> (I suppose its to late to change find_iter, though I think byte offsets have no place in text processing anymore).

I'm not sure I agree with this view. Specifically, in the context of *guaranteed valid UTF-8 byte strings*, byte offsets work swimmingly. A Unicode scalar value offset in that context could be quite restrictive, since slicing then takes linear time. It would be quite strange IMO for a function to take UTF-8 bytes and return Unicode scalar value offsets. If the function instead took a slice of Unicode scalar values, then sure, indexes into that would make sense.

**Comment by Fiedzia** [comment]
Thanks for response. My issue is that I work with codepoints. All text operations I perform (insert this, cut out that, check if those characters are in in this set etc.) operate on codepoints (.chars()), and suddenly regexp points me to a byte offset.
There is .char_at(), but it may be expensive.

Below is some bit I've wrote. It replaces part of text unless its part of 
some words I want to keep.

let mut buf = "some text with uncode ąśćółń".to_owned();
`
let mut protected_positions:Vec<bool> =  vec![false; buf.chars().count()];
        //regexp.find_iter returns ranges as byte positions, we need this logic to translate 
        //those into char indices
        let mut char_positions:Vec<usize> =  vec![0; buf.len()];
        for (ch_idx, (byte_idx, ch)) in buf.char_indices().enumerate() {
            for bi in 0..ch.len_utf8() {
                char_positions[byte_idx + bi] = ch_idx;
            }
        }
        for word in PROTECTED_WORDS.iter() {
            for pos in Regex::new(&quote(word)).unwrap().find_iter(&buf) {
                let (byte_start, byte_end) = pos;
                let (start, end) = (char_positions[byte_start], char_positions[byte_end-1]);
                let mut i = start;
                while i < end {
                     protected_positions[i] = true;
                     i+=1;
                }
            }
        };
        buf = buf.chars().enumerate().map(
            |(idx, ch)| {
                if IGNORE_CHARS.binary_search(&ch).is_ok() && !protected_positions[idx] {' '} else {ch}
            }).collect();
`
The problem is that:
1. Not being able to get codepoint offsets forces me to calculate them myself.
2. This calculation is extremely error prone. I've got dozens of panics before I've got it right. It might be that I'm new to rust, but after coming from python3,
I don't see any reason why any library operating on text would ever use bytes.
Perhaps the assumption that (all) string are bytes in utf8 is a source of the problem.
Could regex accept my alternative string implementation?


> Note that all of the string matching functions in std also return byte offsets!

I am not a fan of that either. I consider this to be source of many issues with handling text.

**Comment by BurntSushi** [comment]
> My issue is that I work with codepoints.

I think this is indeed the issue. Rust's `String` type is *not* a sequence of codepoints. It is a byte string **that is guaranteed to be valid UTF-8**. As such, all string manipulation functions operate on UTF-8 bytes. If you're choosing to operate at the codepoint level, then I don't see how you can both utilize functions in the Rust ecosystem that operate on `String`/`&str` and avoid having a byte<->codepoint map to translate.

>  This calculation is extremely error prone. I've got dozens of panics before I've got it right.

My suggestion would be to put the byte<->char mapping behind an abstraction so that it can be individually tested.

> but after coming from python3

Yup, strings in Python are *very* different than strings in Rust. In Python 3, strings are sequences of Unicode codepoints, so it's natural that any operations on that data type operate in the space of codepoints.

> I don't see any reason why any library operating on text would ever use bytes.

In Python, I'd probably agree with you. Rust is not the only language that deals in bytes. :-)

> Perhaps the assumption that (all) string are bytes in utf8 is a source of the problem.

To clarify, this is not an assumption, it is an *invariant* of the `String`/`&str` types. Values inhabiting that type are guaranteed to be UTF-8.

> Could regex accept my alternative string implementation?

Unfortunately not. It would of course be possible to build an alternative regex implementation that only operated on codepoints, but that is definitely out of scope for this crate. I also speculate that such an implementation could never be as fast as one that knows how to look at raw bytes.

When this crate gets a DFA (hopefully soonish), UTF-8 decoding will actually be built directly into the automaton! :-)

**Comment by Fiedzia** [comment]
> When this crate gets a DFA (hopefully soonish), UTF-8 decoding will actually be built directly into the automaton! :-)

Good to know, thanks.

**Comment by messense** [comment]
Any update on this. Ran into this issue recently.

**Comment by BurntSushi** [comment]
@messense Please provide more details. My comments above should clarify why this isn't something to be "fixed", so you will need to explain your viewpoint. You might consider opening a new issue.

**Comment by messense** [comment]
> When this crate gets a DFA (hopefully soonish), UTF-8 decoding will actually be built directly into the automaton! :-)

@BurntSushi just wondering about this.

**Comment by BurntSushi** [comment]
It's done.
