### ISSUE TITLE
Configure how `regex_syntax` treats `.`, case-sensitivity, etc

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/regex#172]
Currently it seems that `.` is translated to `AnyCharNoNL`, but for my use case I would prefer `AnyChar`. I imagine I could probably achieve this by tweaking the input string to something like `(?s:...)`, but it seems like something that ought to be configurable in a more "first-class" way (among other things, that will mess up the indices in my error messages, unless of course I account for it). Another similar example is being able to control if the regex is case sensitive or not.

**Comment by BurntSushi** [comment]
`.` matching "anything except for new line" is pretty ubiquitous in regex land, which is why it's the default. I think what you're asking for is the ability to change the default values of flags? That seems reasonable. Users could still revert to the "normal" behavior by doing `(?-s:.)`, which would disable the `s` flag by default.

Technically, there is a work around that you should be able to use now: simply prepend your default flag settings to the regex string given to the parser. So for example, given any regex `re`, the regex `(?i)re` would change the default value of the case insensitive flag to true.

With all that said, perhaps there should be an `ExprBuilder` or an `ExprFlags` that would enable one to set the default flag values that the parser uses in a more structured way.

Does this help solve your problem or am I way off track?

**Comment by nikomatsakis** [comment]
> `.` matching "anything except for new line" is pretty ubiquitous in regex land, which is why it's the default

Well I'll be. I was going to say that this is not the case for lexical generations, except I looked up what flex does and it says `.` matches "any character (byte) except newline"

> I think what you're asking for is the ability to change the default values of flags?

Yes, this is precisely what I want.

> That seems reasonable. 

...and I agree that although I should change how `.` behaves to match the current default, this still seems like a pretty useful thing to have.

> Technically, there is a work around that you should be able to use now: simply prepend your default flag settings to the regex string given to the parser. So for example, given any regex re, the regex (?i)re would change the default value of the case insensitive flag to true.

Yeah, I mentioned this potential workaround in my bug report. It seems fine except that then the error messages don't match up as well.

**Comment by BurntSushi** [comment]
I agree this would be nice. Good point about the error messages!

> Yeah, I mentioned this potential workaround in my bug report.

Whoops! Missed that. :-)
