### ISSUE TITLE
Syntax error escaping backslash and double-quotes

### ISSUE THREAD

**Issue by k0pernicus** [rust-lang-nursery/regex#185]
Hi!
I try to parse with a regex an ```a``` HTML's tag, like that:
```
<a href=\"http://mywebsite.com\">Lalalala</a>
```

I try to get the content of the ```href``` attribute (in the example, ```http://mywebsite.com```) with this regex: ```Regex::new(r#"href=\"(<reference>)\""#).unwrap();```, and get the attribute in the ```reference``` field.

The problem is I get this error when I run my program : 
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(Error { pos: 6, surround: "ref=\\\"(<re", kind: UnrecognizedEscape('\"') })', ../src/libcore/result.rs:688
```

Apparently, there is a problem with my regex, but I can't find where is the problem.

Is anyone can help me please?

**Comment by BurntSushi** [comment]
The relevant error message is:

```
Syntax(Error { pos: 6, surround: "ref=\\\"(<re", kind: UnrecognizedEscape('\"') })
```

Indeed, you have a `\"` in your regex, which is an unrecognized escape sequence. `"` isn't a special regex character, so it shouldn't be escaped. Instead, just use `"`.

If you are indeed trying to match the literal `\"` as your original HTML indicates, then since `\` *is* a special regex character, it must be escaped. So to match `\"`, you should use `\\"`.

**Comment by k0pernicus** [comment]
Oh crap - sorry for that... :-/

Thanks a lot! :-)
