### ISSUE TITLE
Option::unwrap() called on None-value in Regex::new()

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang-nursery/regex#257]
AFL found this regex which causes `Regex::new()` in `regex-0.1.71` to call `Option::unwrap()` on a None-value, causing a panic

```
r"[^\D\d]"
```

**Comment by BurntSushi** [comment]
@lukaslueg Thank you for filing all these bugs. I can't wait to fix them. :-)

**Comment by BurntSushi** [comment]
This particular bug is a result of two things:

1. `[^\D\d]` is actually an empty character class, since `[\D\d]` says "match anything" and `[^\D\d]` says "match !anything."
2. The compiler assumes that empty character classes are impossible.

I'd like to fix this by more explicitly banning empty character classes. Other regex engines actually allow them and treat them as "never match anything." It seems more sensible (and more conservative) to just ban them outright.
