### ISSUE TITLE
Slow matching with nested repeats.

### ISSUE THREAD

**Issue by SeanRBurton** [rust-lang-nursery/regex#266]
Matching `Repeat { e: Group { e: Repeat { e: AnyChar, r: Range { min: 5, max: None }, greedy: true }, i: Some(1), name: Some("n") }, r: Range { min: 42, max: None }, greedy: true }` against a long chunk of unicode like

```
"\u{56473}\u{63a75}\u{107c79}\u{7c030}\u{8a7f6}\u{a4f7b}\u{4eea6}\u{ad928}\u{12675}\u{6323f}\u{794a4}\u{817ec}\u{6f713}\u{7914a}\u{10e550}\u{6dc6f}\u{4a8e4}\u{f7a07}\u{231d0}\u{a7e2e}\u{ddb5d}\u{a9ec7}\u{ee178}\u{e5e77}\u{35d57}\u{421c4}\u{d30ce}\u{61027}\u{1052e3}\u{d473a}\u{997e0}\u{3b93d}\u{4596d}\u{983ab}\u{e9363}\u{6d87f}\u{35d63}\u{dbfd6}\u{790b}\u{1097ec}\u{375c6}\u{76e}\u{d3616}\u{25e80}\u{a1544}\u{49aa}\u{fa8e1}\u{f498b}\u{278c3}\u{a6567}\u{9a253}\u{ccff6}\u{7f363}\u{788e4}\u{68c96}\u{b092a}\u{21d45}\u{70377}\u{bdc9d}\u{7c7f7}\u{b05e1}\u{a9abc}\u{91ffb}\u{2496b}\u{309f7}\u{9ff19}\u{1019dc}\u{8ee5}\u{61bed}\u{6eb4}\u{9d7a0}\u{3e68}\u{b8bb3}\u{b23b2}\u{8b706}\u{e72a0}\u{2f0da}\u{9f644}\u{7d228}\u{b1e47}\u{9b255}\u{ad2c1}\u{1a85e}\u{f9380}\u{8d222}\u{85a31}\u{22243}\u{7a07f}\u{336b0}\u{50709}\u{d3c71}\u{35812}\u{1f110}\u{17dc9}\u{1043a7}\u{20eec}\u{dd02d}\u{1825b}\u{786b9}\u{68a4c}\u{2649f}\u{e3f54}\u{2b56c}\u{eefae}\u{c39de}\u{fd8d6}\u{14bea}\u{c1743}\u{562d0}\u{5d75f}\u{8c31d}\u{10e84}\u{c9393}\u{1ea94}\u{609dc}\u{ecfdd}\u{109bdb}\u{c76c0}\u{5a0d8}\u{a6009}\u{36936}\u{8fe4f}\u{2e417}\u{5e762}\u{66cdc}\u{cd361}\u{8a8a3}\u{54ff1}\u{3e58b}\u{5c8e5}\u{8726a}\u{293b}\u{5c096}\u{7f6a4}\u{b30b7}\u{bff6b}\u{ac951}\u{256de}\u{ee51c}\u{c5b5a}\u{cbdbd}\u{7e56c}\u{abf38}\u{80042}\u{10e603}\u{4972b}\u{f3b08}\u{46ab2}\u{e516f}\u{72552}\u{d1320}\u{c1a6c}\u{37379}\u{a97bf}\u{b4b37}\u{13191}\u{9c786}\u{12cba}\u{b75f5}\u{580ae}\u{106904}\u{5a658}\u{35548}\u{220eb}\u{e5322}\u{fba80}\u{5d3b5}\u{55c04}\u{c033a}\u{1028e4}\u{d7d6c}\u{e74e0}\u{8292b}\u{b16bc}\u{c9296}\u{d7f16}\u{da943}\u{3441}\u{b885f}\u{c5286}\u{ac736}\u{b0c0d}\u{8e090}\u{bf655}\u{76a7f}\u{105076}\u{d366b}\u{3bf1b}\u{bf678}\u{b2845}\u{44ab5}\u{1695f}\u{512f1}\u{641ac}\u{524f4}\u{da86e}\u{5e766}\u{7aa16}\u{6c089}\u{980fd}\u{ee174}\u{1f992}\u{4a706}\u{35303}\u{9e036}\u{104df9}\u{ade5b}\u{e08a0}\u{2a022}\u{5f937}\u{61c67}\u{5c583}\u{67900}\u{29fbd}\u{5a651}\u{101721}\u{c65a2}\u{d3c10}\u{47369}\u{353f9}\u{3f28c}\u{67e9b}\u{cac74}\u{c05f9}\u{92962}\u{e0f4e}\u{ca97f}\u{c1755}\u{d5051}\u{7fd5b}\u{a93b0}\u{f37bf}\u{4917}\u{2506e}\u{3d14b}\u{e9117}\u{278b1}\u{71d9f}\u{70e66}\u{44502}\u{fc996}\u{8e759}\u{ce17f}\u{f59e6}\u{1017f1}\u{ecdcf}\u{d7146}\u{255c3}\u{767}\u{f467b}"
```

takes a long time (about 2 seconds for 250 characters on my machine). I'm not certain that this is superlinear behaviour, but it seems very slow. This structure of repeat-group-repeat seems to be necessary to reproduce this problem.

**Comment by BurntSushi** [comment]
Could you please provide the actual pattern that's being used? It's too hard to read the AST. (The AST is good to provide to reduce ambiguity, thank you, but please also include the actual pattern.)

If you do indeed have nested repeats, then I don't see how that results in superlinear behavior. A regex like `a{1000}` is equivalent in every way to `a` repeated 1,000 times, so the size the of regex is proportional to `a` 1,000 times as opposed to the literal string `a{1000}`. If you *nest* repeats, then you end up with multiplicative explosion. i.e., `(a{100}){100}` is equivalent to `a{10000}`.

In any case, repeats are precisely the case where DFAs perform poorly, because they typically require many states. Lots of states means more memory. If you have enough states, the DFA will fall over and you'll revert to the Pike VM NFA, which is already about an order of magnitude slower than the DFA.

**Comment by SeanRBurton** [comment]
Here's a similar regex with the same behaviour: `"((?su:.){5,}){42,}?"`.

**Comment by BurntSushi** [comment]
So you're right that a regex like `(.{5,}){42,}` is slow. DFAs do really badly on big repeats because it needs to build lots of states. With this regex, by the time it's done searching 2GB of text, it has 349 states and every state has a huge number of instruction pointers in it. Here's a small sample, where the number on the left is the state index and the number on the right is the number of NFA states (i.e., instruction pointers) in the DFA state:

```
  0: 3
  1: 5
  2: 7
  3: 9
  4: 11
  5: 15
  6: 17
  7: 19
  8: 21
  9: 23
  10: 27
  11: 29
  12: 31
  13: 33
  14: 35
  15: 39
  ...
  331: 435
  332: 441
  333: 443
  334: 447
  335: 449
  336: 451
  337: 453
  338: 461
  339: 463
  340: 465
  341: 467
  342: 479
  343: 483
  344: 485
  345: 489
  346: 491
  347: 495
  348: 499
  349: 501
```

This is made a lot worse because of `.`, which matches *any* character, so the states keep building and building. Remember, in the lazy DFA, the *haystack* can influence the size of the DFA, which is why we bound it . For example, if we change the regex to `(a{5,}){42,}`, then searching the same text results in the creation of only 10 states:

```
  0: 2
  1: 3
  2: 4
  3: 5
  4: 6
  5: 8
  6: 9
  7: 10
  8: 2
  9: 11
```

This is probably because the input never has more than 10 consecutive `a`s in a row (indeed, I confirmed that it has one match for `a{9}` but none for `a{10}`), so the DFA never needed to build more states to match more than 10 consecutive `a`s. In contrast, using `.` will all but guarantee getting a number of DFA states roughly proportional to the number of times `.` is repeated because it matches everything.

Let's bring this back to reality. Consider GNU grep, a known fast regex implementation. We'll search that same 2GB of text:

```
$ time xrep -c '(.{5,}){42,}' all
55223

real    0m4.008s
user    0m3.907s
sys     0m0.097s
$ time LC_ALL=en_US.UTF-8 egrep -a -c '(.{5,}){42,}' all
55223

real    0m9.529s
user    0m9.227s
sys     0m0.297s
```

Lest we believe this crate is just better at Unicode, let's do byte based matching too:

```
$ time xrep -c '((?-u:.){5,}){42,}' all
59350

real    0m3.932s
user    0m3.810s
sys     0m0.117s
$ time LC_ALL=C egrep -a -c '(.{5,}){42,}' all
59350

real    0m7.933s
user    0m7.677s
sys     0m0.250s
```

So despite this crate being slow on these regexes, it is still faster than GNU grep on the same regexes. To me, that implies we aren't doing too badly.
