### ISSUE TITLE
implement &T for Replacer where T: Replacer

### ISSUE THREAD

**Issue by RCIX** [rust-lang-nursery/regex#83]
When attempting to call replace_all on a Regex with a str as the argument for rep(as opposed to a NoExpand), the Replacer trait implementation for str is apparently being ignored, instead falling back to the FnMut implementation. [This project](https://github.com/RCIX/regex_replace_error) demonstrates the following compile error:

    src\main.rs:13:23: 13:53 error: the trait `for<'r,'r> core::ops::Fn<(&'r regex::re::Captures<'r>,)>` is not implemented for the type `str` [E0277]
    src\main.rs:13         true => regex.replace_all(&source, &replace.as_str()),
 
Where replace and source are both Strings.

Edit: just fixed the type of replace by adding as_str, as the & was not coercing the String to a str properly. See the latest commit.

**Comment by BurntSushi** [comment]
If you use `replace.as_str()` instead of `&replace.as_str()`, then your code works. The `as_str` method returns a `&str`, so `&replace.as_str()` has type `&&str`, and no impl for that exists.

I wonder if we can add a `impl<'a, T: Replacer> &'a T for Replacer { ... }` impl that would fix this. The standard library uses this convention AFAIK.

**Comment by BurntSushi** [comment]
I feel like it's probably not worth adding this impl unless there's a more solid reason. (It could be added in a backwards compatible manner later if we really wanted to, I think.)
